version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=sqlite
      - CACHE_STORE=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - APP_DEBUG=false
    volumes:
      - ./database:/var/www/html/database