[phases.setup]
nixPkgs = ["php82", "php82Extensions.sqlite3"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "touch /app/database/database.sqlite && chmod -R 775 /app/database && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"