services:
  - type: web
    name: laravel-web-ejemplo
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    disk:
      name: laravel-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: DB_SSLMODE
        value: require  
